# Generated by Django 2.0.2 on 2019-05-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.PositiveIntegerField()),
                ('emp_name', models.CharField(max_length=64)),
                ('emp_sal', models.FloatField()),
            ],
        ),
    ]
